### ISSUE TITLE
I want to comapre only a particular schema in source and destination using dacapac not all schemas

### ISSUE THREAD

**Issue by ashishdahiya225** [Azure/sql-action#182] opened 2023-06-19 14:47 UTC

**Comment by dzsquared** [comment] 2023-06-23 22:18
Issue for https://github.com/microsoft/dacfx, not specific to sql-action on GitHub

Likely duplicate of https://github.com/microsoft/DacFx/issues/24, if so feel free to vote or drop a note on it

**Closed by dzsquared** 2023-06-23 22:18 UTC
Labels: need-to-triage
