### ISSUE TITLE
detectIPAddress method results in error due to db name not being specified

### ISSUE THREAD

**Issue by ypatel-insight** [Azure/sql-action#79] opened 2022-02-22 18:15 UTC
The SqlUtils.detectIPAddress method that is testing the connection results in the following error... 

`The server principal "(db name)" is not able to access the database "master" under the current security context...`

due to the database name not being specified. Can `-d "${connectionString.database}` be added to the following line?

https://github.com/Azure/sql-action/blob/50fc311305fb1d3eb3398bcd21eefe39daa316ed/src/SqlUtils.ts#L15

**Comment by dzsquared** [comment] 2022-04-12 20:44
closing as a duplicate of #89

**Closed by dzsquared** 2022-04-12 20:44 UTC
Labels: enhancement
